apiVersion: v2
name: nvidia-gpu-exporter
description: A Helm chart for NVIDIA GPU exporter
keywords:
  - nvidia-gpu-exporter
  - prometheus
  - exporter
type: application
version: 0.1.3
appVersion: 0.1.3
home: https://github.com/V01d42/nvidia-gpu-exporter
sources:
  - https://github.com/V01d42/nvidia-gpu-exporter
maintainers:
  - name: v01d42
    url: https://github.com/v01d42
